
export const FETCH_POSTERS_REQUEST = 'FETCH_POSTERS_REQUEST';
export const FETCH_POSTERS_SUCCESS = 'FETCH_POSTERS_SUCCESS';
export const FETCH_POSTERS_FAILURE = 'FETCH_POSTERS_FAILURE';

export const FETCH_SEARCH_TERM = 'FETCH_SEARCH_TERM';


export const FETCH_POSTER_DETAIL = 'FETCH_POSTER_DETAIL';
export const FETCH_POSTER_DETAIL_SUCCESS = 'FETCH_POSTER_DETAIL_SUCCESS';
export const FETCH_POSTER_DETAIL_FAILURE = 'FETCH_POSTERS_FAILURE';

